---
- name: "Stop Apache"
  hosts: Mongo
  gather_facts: true 
  become: true
  tasks: 
    - 
      name: stop apache
      service: 
        name: httpd
        state: stopped
      name: status Apache
      service:
        name: httpd status
        tasks: 
          - action: command "ps -ef |grep -i httpd"
...
    
