---
- name: restarting multiple services
  hosts: ies007nlamngopsm
  become: true
  tasks:
    - name: restarting systemd
      systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - httpd
        - postfix
        - rsyslog
...
