---
- name: System services status
  hosts: all
  tasks:
    - name: Get Service Status
      ansible.builtin.systemd:
        name: "httpd"
      register: ht_service_status

     - debug:
         var: ht_service_status.status.ActiveState
