---
- name: System services status
  hosts: all
  tasks:
    - name: service status
      command: systemctl status "{{ item }}"
      with_items:
      - firewalld
      - httpd
      - vsftpd
      - sshd
      - postfix
      register: result
      ignore_errors: yes
    - name: showing report
      debug:
      var: result
